{% set name = "anybadge" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anybadge-{{ version }}.tar.gz
  sha256: 04c2adf57ab8b2cf503b89883b21214bce3a6418a7c8185096b1535aa2d019ae

build:
  entry_points:
    - anybadge=anybadge.cli:main
    - anybadge-server=anybadge.server.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7

  run:
    - packaging
    - python >=3.7

test:
  imports:
    - anybadge
    - anybadge_server
  commands:
    - pip check
    - anybadge --help
    - anybadge-server --help
  requires:
    - pip

about:
  home: https://github.com/jongracecox/anybadge
  summary: Simple, flexible badge generator for project badges.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
